CONVERSÃO DOLAR
# https://drive.google.com/file/d/1zlUgHm_7-nlbLrr43AjpSFoff2w3V8TQ/view?usp=sharing
---------------------------------------------------------------------------------------
POTENCIA
#
---------------------------------------------------------------------------------------
COMISSÃO
# https://drive.google.com/file/d/1-TPX24XZMx7oSYhnhX3aaYdVmievE2q8/view?usp=sharing
---------------------------------------------------------------------------------------
CUSTO CARRO
# https://drive.google.com/file/d/1ySj6YU0VXi8wE8lWbJCevmHzTJQpcaMV/view?usp=sharing
---------------------------------------------------------------------------------------
CONVERSAO HORAS
# https://drive.google.com/file/d/1f5gbJBogVWsBmdTBKgW3pSEZ0Pn4UmPq/view?usp=sharing
---------------------------------------------------------------------------------------
HORA EXTRA
# https://drive.google.com/file/d/1yF52G_HROiS-8QL0oGbxFbT5bbdlqfce/view?usp=sharing
---------------------------------------------------------------------------------------
COMBUSTIVEL - GASOLINA
# https://drive.google.com/file/d/1-cMbHm-yr4ESZHqf39UK9kE4neaVXqKl/view?usp=sharing
---------------------------------------------------------------------------------------
VELOCIDADE MEDIA
# https://drive.google.com/file/d/16bfB3ZM21L-iYhVPvLWPiFAO-nVvwP54/view?usp=sharing
---------------------------------------------------------------------------------------
