Algoritmo "areadoparalelogramo"
// 
//  
// Descrição   : atv algoritmos variaveis, area do paralelogramo
// Autor(a)    : Maria Eduarda Orsi Pinto
// Data atual  : 11/03/2021
Var
base, altura, area : real


Inicio
escreval ("digite a base para calcular a area do paralelogramo")
leia (base)
escreval ("digite a altura para calcular a area do paralelogramo")
leia (altura)
area <- altura*base

escreval ("a area do paralelogramo e:", area ,"m2")


Fimalgoritmo