Algoritmo "areadoretangulo"
// 
//  
// Descrição   : Area do retângulo atividade algoritmos variaveis e operadores aritmedicos
// Autor(a)    : Maria Eduarda Orsi Pinto
// Data atual  : 11/03/2021
Var
base, altura, area: real


Inicio
escreval ("digite a base do retangulo:")
leia (base)
escreval ("digite a altura do retangulo:")
leia (altura)

area <- base *altura
escreval (" a area do retangulo e:" ,area,"m2")


Fimalgoritmo